### ISSUE TITLE
worlds.events.tick <- worlds belitrilmemiş 

### ISSUE THREAD

**Issue by uwuv3** [xTendou/TendouAntiCheat#1]
Bence orası

`world.events.tick.subscribe((data) => {
  for (const player of world.getPlayers()) {
    let rightInventoryComp = player.getComponent("minecraft:inventory");

    let rightChestContainer = rightInventoryComp.container;

    let item = rightChestContainer.getItem(player.selectedSlot);

    if (ilegalBlocks.includes(item.id)) {
      player.runCommand(`tag @s add banned`);
    }
  }
});`

olacaktı

**Comment by hzTendou** [comment]
Düzeltiyorum hemen belirtdiğin için teşekkürler
